import React from "react";
import Product_card from "../components/Product-card";
import e_commerce from "../assets/e-commerce.png";
import task from "../assets/Task - Manager.png";
import analytics from "../assets/analytics.png";
import blog from "../assets/blog.png";

const projects = [
    {
        id: 1,
        department: "Computer Science",
        course: "IT",
        level: "Beginner",
        image: e_commerce,
        name: "E-commerce",
        paragraph: "A full-Stack e-commerce web app with cart, orders and payments",
        Tech_1: "HTML",
        Tech_2: "CSS",
        Tech_3: "JavaScript",
        Days: "10 Days",
        rating: "4.6",
        views: "(120)",
        bg1: "bg-red-200",
        text1: "text-red-600",
        bg2: "bg-purple-200",
        text2: "text-purple-600",
        bg3: "bg-fuchsia-200",
        text3: "text-fuchsia-600",
    },
    {
        id: 2,
        department: "Computer Science",
        course: "IT",
        level: "Intermediate",
        image: task,
        name: "Task Manager",
        paragraph: "A full-Stack e-commerce web app with cart, orders and payments",
        Tech_1: "React",
        Tech_2: "Tailwind",
        Tech_3: "JavaScript",
        Days: "7 Days",
        rating: "4.7",
        views: "(98)",
        bg1: "bg-orange-200",
        text1: "text-orange-600",
        bg2: "bg-yellow-200",
        text2: "text-yellow-600",
        bg3: "bg-red-200",
        text3: "text-red-600",
    },
    {
        id: 3,
        department: "Computer Science",
        course: "DS",
        level: "Advanced",
        image: analytics,
        name: "Analytics Dashboard",
        paragraph: "A full-Stack e-commerce web app with cart, orders and payments",
        Tech_1: "Next.js",
        Tech_2: "TypeScript",
        Tech_3: "Chart.js",
        Days: "7 Days",
        rating: "4.7",
        views: "(98)",
        bg1: "bg-orange-200",
        text1: "text-orange-600",
        bg2: "bg-yellow-200",
        text2: "text-yellow-600",
        bg3: "bg-red-200",
        text3: "text-red-600",
    },
    {
        id: 4,
        department: "Computer Science",
        course: "IT",
        level: "Intermediate",
        image: blog,
        name: "Blog",
        paragraph: "A full-Stack e-commerce web app with cart, orders and payments",
        Tech_1: "React",
        Tech_2: "Tailwind",
        Tech_3: "JavaScript",
        Days: "7 Days",
        rating: "4.7",
        views: "(98)",
        bg1: "bg-orange-200",
        text1: "text-orange-600",
        bg2: "bg-yellow-200",
        text2: "text-yellow-600",
        bg3: "bg-red-200",
        text3: "text-red-600",
    },
    {
        id: 5,
        department: "Computer Science",
        course: "AI",
        level: "Advanced",
        image: analytics,
        name: "AI Chatbot",
        paragraph: "An AI-powered chatbot that can answer user questions and provide smart responses",
        Tech_1: "Python",
        Tech_2: "OpenAI API",
        Tech_3: "FastAPI",
        Days: "12 Days",
        rating: "4.8",
        views: "(150)",
        bg1: "bg-green-200",
        text1: "text-green-600",
        bg2: "bg-blue-200",
        text2: "text-blue-600",
        bg3: "bg-purple-200",
        text3: "text-purple-600",
    },
    {
        id: 6,
        department: "Computer Science",
        course: "IT",
        level: "Beginner",
        image: blog,
        name: "Portfolio Website",
        paragraph: "A responsive personal portfolio website to showcase skills, projects and experience",
        Tech_1: "HTML",
        Tech_2: "CSS",
        Tech_3: "JavaScript",
        Days: "5 Days",
        rating: "4.6",
        views: "(85)",
        bg1: "bg-cyan-200",
        text1: "text-cyan-600",
        bg2: "bg-indigo-200",
        text2: "text-indigo-600",
        bg3: "bg-pink-200",
        text3: "text-pink-600",
    },

    {
        id: 7,
        department: "Computer Science",
        course: "DS",
        level: "Intermediate",
        image: task,
        name: "Expense Tracker",
        paragraph: "A web app to track daily expenses, manage spending and view expense summaries",
        Tech_1: "React",
        Tech_2: "JavaScript",
        Tech_3: "Tailwind",
        Days: "8 Days",
        rating: "4.7",
        views: "(92)",
        bg1: "bg-emerald-200",
        text1: "text-emerald-600",
        bg2: "bg-yellow-200",
        text2: "text-yellow-600",
        bg3: "bg-violet-200",
        text3: "text-violet-600",
    },

    {
        id: 8,
        department: "Computer Science",
        course: "AI",
        level: "Intermediate",
        image: analytics,
        name: "AI Assistant",
        paragraph: "An intelligent assistant that can answer questions and provide useful responses",
        Tech_1: "Python",
        Tech_2: "OpenAI API",
        Tech_3: "FastAPI",
        Days: "10 Days",
        rating: "4.8",
        views: "(110)",
        bg1: "bg-sky-200",
        text1: "text-sky-600",
        bg2: "bg-orange-200",
        text2: "text-orange-600",
        bg3: "bg-blue-200",
        text3: "text-blue-600",
    },

    {
        id: 9,
        department: "Computer Science",
        course: "ML",
        level: "Advanced",
        image: e_commerce,
        name: "Prediction System",
        paragraph: "A machine learning project that analyzes data and predicts future outcomes",
        Tech_1: "Python",
        Tech_2: "Scikit-learn",
        Tech_3: "Pandas",
        Days: "15 Days",
        rating: "4.9",
        views: "(134)",
        bg1: "bg-rose-200",
        text1: "text-rose-600",
        bg2: "bg-teal-200",
        text2: "text-teal-600",
        bg3: "bg-purple-200",
        text3: "text-purple-600",
    },
    {
        id: 10,
        department: "Science",
        course: "Physics",
        level: "Beginner",
        image: e_commerce,
        name: "Physics Experiment Simulator",
        paragraph: "An interactive simulator for learning basic physics experiments and concepts",
        Tech_1: "HTML",
        Tech_2: "CSS",
        Tech_3: "JavaScript",
        Days: "7 Days",
        rating: "4.6",
        views: "(85)",
        bg1: "bg-blue-200",
        text1: "text-blue-600",
        bg2: "bg-purple-200",
        text2: "text-purple-600",
        bg3: "bg-cyan-200",
        text3: "text-cyan-600",
    },

    {
        id: 11,
        department: "Science",
        course: "Chemistry",
        level: "Intermediate",
        image: e_commerce,
        name: "Chemistry Lab",
        paragraph: "A virtual chemistry lab for exploring chemical reactions and experiments",
        Tech_1: "React",
        Tech_2: "Tailwind",
        Tech_3: "JavaScript",
        Days: "10 Days",
        rating: "4.7",
        views: "(102)",
        bg1: "bg-green-200",
        text1: "text-green-600",
        bg2: "bg-blue-200",
        text2: "text-blue-600",
        bg3: "bg-yellow-200",
        text3: "text-yellow-600",
    },

    {
        id: 12,
        department: "Science",
        course: "Botany",
        level: "Intermediate",
        image: e_commerce,
        name: "Biology Explorer",
        paragraph: "An interactive learning platform to explore cells, organs and biological concepts",
        Tech_1: "React",
        Tech_2: "CSS",
        Tech_3: "JavaScript",
        Days: "8 Days",
        rating: "4.5",
        views: "(76)",
        bg1: "bg-green-200",
        text1: "text-green-600",
        bg2: "bg-pink-200",
        text2: "text-pink-600",
        bg3: "bg-purple-200",
        text3: "text-purple-600",
    },

    {
        id: 13,
        department: "Science",
        course: "Maths",
        level: "Beginner",
        image: e_commerce,
        name: "Scientific Calculator",
        paragraph: "A scientific calculator for performing mathematical and scientific calculations",
        Tech_1: "HTML",
        Tech_2: "CSS",
        Tech_3: "JavaScript",
        Days: "5 Days",
        rating: "4.8",
        views: "(135)",
        bg1: "bg-orange-200",
        text1: "text-orange-600",
        bg2: "bg-blue-200",
        text2: "text-blue-600",
        bg3: "bg-purple-200",
        text3: "text-purple-600",
    },

    {
        id: 14,
        department: "Science",
        course: "Zoology",
        level: "Advanced",
        image: e_commerce,
        name: "Scientific Data Analysis",
        paragraph: "A data analysis dashboard for visualizing and interpreting scientific data",
        Tech_1: "Python",
        Tech_2: "Pandas",
        Tech_3: "Chart.js",
        Days: "12 Days",
        rating: "4.9",
        views: "(160)",
        bg1: "bg-indigo-200",
        text1: "text-indigo-600",
        bg2: "bg-green-200",
        text2: "text-green-600",
        bg3: "bg-yellow-200",
        text3: "text-yellow-600",
    },
    {
        id: 15,
        department: "Science",
        course: "Physics",
        level: "Intermediate",
        image: e_commerce,
        name: "Motion Analyzer",
        paragraph: "An interactive project for analyzing motion, speed and acceleration",
        Tech_1: "HTML",
        Tech_2: "CSS",
        Tech_3: "JavaScript",
        Days: "8 Days",
        rating: "4.7",
        views: "(90)",
        bg1: "bg-sky-200",
        text1: "text-sky-600",
        bg2: "bg-indigo-200",
        text2: "text-indigo-600",
        bg3: "bg-purple-200",
        text3: "text-purple-600",
    },

    {
        id: 16,
        department: "Science",
        course: "Chemistry",
        level: "Beginner",
        image: e_commerce,
        name: "Periodic Table Explorer",
        paragraph: "An interactive periodic table for exploring elements and their properties",
        Tech_1: "HTML",
        Tech_2: "CSS",
        Tech_3: "JavaScript",
        Days: "6 Days",
        rating: "4.6",
        views: "(82)",
        bg1: "bg-green-200",
        text1: "text-green-600",
        bg2: "bg-yellow-200",
        text2: "text-yellow-600",
        bg3: "bg-orange-200",
        text3: "text-orange-600",
    },

    {
        id: 17,
        department: "Science",
        course: "Botany",
        level: "Advanced",
        image: e_commerce,
        name: "Plant Growth Tracker",
        paragraph: "A dashboard for tracking plant growth and analyzing environmental conditions",
        Tech_1: "React",
        Tech_2: "Tailwind",
        Tech_3: "Chart.js",
        Days: "10 Days",
        rating: "4.8",
        views: "(115)",
        bg1: "bg-emerald-200",
        text1: "text-emerald-600",
        bg2: "bg-lime-200",
        text2: "text-lime-600",
        bg3: "bg-green-200",
        text3: "text-green-600",
    },

    {
        id: 18,
        department: "Science",
        course: "Maths",
        level: "Intermediate",
        image: e_commerce,
        name: "Math Problem Solver",
        paragraph: "An interactive application for solving and practicing mathematical problems",
        Tech_1: "React",
        Tech_2: "CSS",
        Tech_3: "JavaScript",
        Days: "7 Days",
        rating: "4.7",
        views: "(105)",
        bg1: "bg-violet-200",
        text1: "text-violet-600",
        bg2: "bg-blue-200",
        text2: "text-blue-600",
        bg3: "bg-pink-200",
        text3: "text-pink-600",
    },
    {
        id: 19,
        department: "Arts",
        course: "Tamil",
        level: "Beginner",
        image: e_commerce,
        name: "Tamil Literature Explorer",
        paragraph: "An interactive platform to explore Tamil literature, poems and famous works",
        Tech_1: "HTML",
        Tech_2: "CSS",
        Tech_3: "JavaScript",
        Days: "6 Days",
        rating: "4.6",
        views: "(82)",
        bg1: "bg-orange-200",
        text1: "text-orange-600",
        bg2: "bg-red-200",
        text2: "text-red-600",
        bg3: "bg-yellow-200",
        text3: "text-yellow-600",
    },

    {
        id: 20,
        department: "Arts",
        course: "Tamil",
        level: "Intermediate",
        image: e_commerce,
        name: "Tamil Quiz App",
        paragraph: "A quiz application to practice Tamil grammar, literature and general knowledge",
        Tech_1: "React",
        Tech_2: "CSS",
        Tech_3: "JavaScript",
        Days: "7 Days",
        rating: "4.7",
        views: "(96)",
        bg1: "bg-rose-200",
        text1: "text-rose-600",
        bg2: "bg-orange-200",
        text2: "text-orange-600",
        bg3: "bg-pink-200",
        text3: "text-pink-600",
    },

    {
        id: 21,
        department: "Arts",
        course: "English",
        level: "Beginner",
        image: e_commerce,
        name: "English Learning App",
        paragraph: "A simple platform to improve English vocabulary, grammar and communication skills",
        Tech_1: "HTML",
        Tech_2: "Tailwind",
        Tech_3: "JavaScript",
        Days: "8 Days",
        rating: "4.8",
        views: "(120)",
        bg1: "bg-blue-200",
        text1: "text-blue-600",
        bg2: "bg-indigo-200",
        text2: "text-indigo-600",
        bg3: "bg-purple-200",
        text3: "text-purple-600",
    },

    {
        id: 22,
        department: "Arts",
        course: "English",
        level: "Intermediate",
        image: e_commerce,
        name: "Vocabulary Builder",
        paragraph: "An interactive application for learning and practicing new English words",
        Tech_1: "React",
        Tech_2: "Tailwind",
        Tech_3: "JavaScript",
        Days: "6 Days",
        rating: "4.6",
        views: "(88)",
        bg1: "bg-cyan-200",
        text1: "text-cyan-600",
        bg2: "bg-blue-200",
        text2: "text-blue-600",
        bg3: "bg-violet-200",
        text3: "text-violet-600",
    },

    {
        id: 23,
        department: "Arts",
        course: "History",
        level: "Beginner",
        image: e_commerce,
        name: "History Timeline",
        paragraph: "An interactive timeline to explore important historical events and personalities",
        Tech_1: "HTML",
        Tech_2: "CSS",
        Tech_3: "JavaScript",
        Days: "7 Days",
        rating: "4.7",
        views: "(91)",
        bg1: "bg-amber-200",
        text1: "text-amber-600",
        bg2: "bg-yellow-200",
        text2: "text-yellow-600",
        bg3: "bg-orange-200",
        text3: "text-orange-600",
    },

    {
        id: 24,
        department: "Arts",
        course: "History",
        level: "Advanced",
        image: e_commerce,
        name: "Historical Map Explorer",
        paragraph: "A visual application for exploring historical places, regions and major events",
        Tech_1: "React",
        Tech_2: "JavaScript",
        Tech_3: "Leaflet",
        Days: "10 Days",
        rating: "4.8",
        views: "(105)",
        bg1: "bg-stone-200",
        text1: "text-stone-600",
        bg2: "bg-orange-200",
        text2: "text-orange-600",
        bg3: "bg-amber-200",
        text3: "text-amber-600",
    },

    {
        id: 25,
        department: "Arts",
        course: "Economics",
        level: "Intermediate",
        image: e_commerce,
        name: "Budget Planner",
        paragraph: "A simple application to manage personal budgets, income and expenses",
        Tech_1: "React",
        Tech_2: "Tailwind",
        Tech_3: "JavaScript",
        Days: "8 Days",
        rating: "4.7",
        views: "(98)",
        bg1: "bg-green-200",
        text1: "text-green-600",
        bg2: "bg-emerald-200",
        text2: "text-emerald-600",
        bg3: "bg-teal-200",
        text3: "text-teal-600",
    },

    {
        id: 26,
        department: "Arts",
        course: "Economics",
        level: "Advanced",
        image: e_commerce,
        name: "Economic Data Dashboard",
        paragraph: "A dashboard for visualizing economic data, trends and financial statistics",
        Tech_1: "React",
        Tech_2: "Chart.js",
        Tech_3: "JavaScript",
        Days: "12 Days",
        rating: "4.9",
        views: "(132)",
        bg1: "bg-blue-200",
        text1: "text-blue-600",
        bg2: "bg-green-200",
        text2: "text-green-600",
        bg3: "bg-cyan-200",
        text3: "text-cyan-600",
    },

    {
        id: 27,
        department: "Arts",
        course: "English",
        level: "Advanced",
        image: e_commerce,
        name: "Online Dictionary",
        paragraph: "A searchable dictionary application for finding word meanings and examples",
        Tech_1: "Next.js",
        Tech_2: "TypeScript",
        Tech_3: "API",
        Days: "10 Days",
        rating: "4.8",
        views: "(115)",
        bg1: "bg-purple-200",
        text1: "text-purple-600",
        bg2: "bg-pink-200",
        text2: "text-pink-600",
        bg3: "bg-blue-200",
        text3: "text-blue-600",
    },
    {
        id: 28,
        department: "Engineering",
        course: "CSE",
        level: "Beginner",
        image: e_commerce,
        name: "Student Management System",
        paragraph: "A web application to manage student records, courses and academic information",
        Tech_1: "HTML",
        Tech_2: "CSS",
        Tech_3: "JavaScript",
        Days: "8 Days",
        rating: "4.6",
        views: "(92)",
        bg1: "bg-blue-200",
        text1: "text-blue-600",
        bg2: "bg-purple-200",
        text2: "text-purple-600",
        bg3: "bg-cyan-200",
        text3: "text-cyan-600",
    },

    {
        id: 29,
        department: "Engineering",
        course: "CSE",
        level: "Intermediate",
        image: task,
        name: "Coding Practice Platform",
        paragraph: "An online platform for practicing programming problems and improving coding skills",
        Tech_1: "React",
        Tech_2: "Tailwind",
        Tech_3: "JavaScript",
        Days: "10 Days",
        rating: "4.8",
        views: "(125)",
        bg1: "bg-indigo-200",
        text1: "text-indigo-600",
        bg2: "bg-blue-200",
        text2: "text-blue-600",
        bg3: "bg-violet-200",
        text3: "text-violet-600",
    },

    {
        id: 30,
        department: "Engineering",
        course: "ECE",
        level: "Beginner",
        image: analytics,
        name: "Circuit Simulator",
        paragraph: "An interactive simulator for learning basic electronic circuits and components",
        Tech_1: "HTML",
        Tech_2: "CSS",
        Tech_3: "JavaScript",
        Days: "7 Days",
        rating: "4.7",
        views: "(88)",
        bg1: "bg-green-200",
        text1: "text-green-600",
        bg2: "bg-cyan-200",
        text2: "text-cyan-600",
        bg3: "bg-blue-200",
        text3: "text-blue-600",
    },

    {
        id: 31,
        department: "Engineering",
        course: "ECE",
        level: "Advanced",
        image: analytics,
        name: "IoT Monitoring Dashboard",
        paragraph: "A dashboard for monitoring IoT devices and displaying real-time sensor data",
        Tech_1: "React",
        Tech_2: "Chart.js",
        Tech_3: "JavaScript",
        Days: "12 Days",
        rating: "4.9",
        views: "(110)",
        bg1: "bg-purple-200",
        text1: "text-purple-600",
        bg2: "bg-pink-200",
        text2: "text-pink-600",
        bg3: "bg-blue-200",
        text3: "text-blue-600",
    },

    {
        id: 32,
        department: "Engineering",
        course: "EEE",
        level: "Intermediate",
        image: e_commerce,
        name: "Power Consumption Tracker",
        paragraph: "An application for tracking and analyzing electrical power consumption",
        Tech_1: "React",
        Tech_2: "Tailwind",
        Tech_3: "Chart.js",
        Days: "9 Days",
        rating: "4.7",
        views: "(95)",
        bg1: "bg-yellow-200",
        text1: "text-yellow-600",
        bg2: "bg-orange-200",
        text2: "text-orange-600",
        bg3: "bg-red-200",
        text3: "text-red-600",
    },

    {
        id: 33,
        department: "Engineering",
        course: "EEE",
        level: "Advanced",
        image: analytics,
        name: "Energy Monitoring Dashboard",
        paragraph: "A dashboard for monitoring energy usage and analyzing electrical data",
        Tech_1: "React",
        Tech_2: "TypeScript",
        Tech_3: "Chart.js",
        Days: "12 Days",
        rating: "4.8",
        views: "(108)",
        bg1: "bg-amber-200",
        text1: "text-amber-600",
        bg2: "bg-green-200",
        text2: "text-green-600",
        bg3: "bg-emerald-200",
        text3: "text-emerald-600",
    },

    {
        id: 34,
        department: "Engineering",
        course: "Civil",
        level: "Beginner",
        image: e_commerce,
        name: "Construction Cost Calculator",
        paragraph: "A calculator for estimating construction materials and project costs",
        Tech_1: "HTML",
        Tech_2: "CSS",
        Tech_3: "JavaScript",
        Days: "6 Days",
        rating: "4.6",
        views: "(78)",
        bg1: "bg-orange-200",
        text1: "text-orange-600",
        bg2: "bg-yellow-200",
        text2: "text-yellow-600",
        bg3: "bg-amber-200",
        text3: "text-amber-600",
    },

    {
        id: 35,
        department: "Engineering",
        course: "Civil",
        level: "Intermediate",
        image: analytics,
        name: "Building Project Planner",
        paragraph: "A project planning tool for managing construction tasks, materials and timelines",
        Tech_1: "React",
        Tech_2: "Tailwind",
        Tech_3: "JavaScript",
        Days: "10 Days",
        rating: "4.7",
        views: "(86)",
        bg1: "bg-stone-200",
        text1: "text-stone-600",
        bg2: "bg-orange-200",
        text2: "text-orange-600",
        bg3: "bg-yellow-200",
        text3: "text-yellow-600",
    },

    {
        id: 36,
        department: "Engineering",
        course: "CSE",
        level: "Advanced",
        image: analytics,
        name: "Engineering Project Dashboard",
        paragraph: "A dashboard for tracking engineering projects, tasks, progress and deadlines",
        Tech_1: "Next.js",
        Tech_2: "TypeScript",
        Tech_3: "Chart.js",
        Days: "14 Days",
        rating: "4.9",
        views: "(140)",
        bg1: "bg-violet-200",
        text1: "text-violet-600",
        bg2: "bg-blue-200",
        text2: "text-blue-600",
        bg3: "bg-indigo-200",
        text3: "text-indigo-600",
    },
    {
        id: 37,
        department: "Commerce",
        course: "B.Com",
        level: "Beginner",
        image: e_commerce,
        name: "Online Bookkeeping System",
        paragraph: "A simple application for managing business transactions, income and expenses",
        Tech_1: "Excel",
        Tech_2: "SQL",
        Tech_3: "Power BI",
        Days: "7 Days",
        rating: "4.6",
        views: "(84)",
        bg1: "bg-blue-200",
        text1: "text-blue-600",
        bg2: "bg-green-200",
        text2: "text-green-600",
        bg3: "bg-purple-200",
        text3: "text-purple-600",
    },

    {
        id: 38,
        department: "Commerce",
        course: "B.Com",
        level: "Intermediate",
        image: task,
        name: "Inventory Management",
        paragraph: "A web application for managing products, stock levels and inventory records",
        Tech_1: "Excel",
        Tech_2: "SQL",
        Tech_3: "Power BI",
        Days: "10 Days",
        rating: "4.8",
        views: "(112)",
        bg1: "bg-orange-200",
        text1: "text-orange-600",
        bg2: "bg-yellow-200",
        text2: "text-yellow-600",
        bg3: "bg-green-200",
        text3: "text-green-600",
    },

    {
        id: 39,
        department: "Commerce",
        course: "CA",
        level: "Intermediate",
        image: analytics,
        name: "Financial Report Dashboard",
        paragraph: "A dashboard for analyzing financial data, income, expenses and business performance",
        Tech_1: "Excel",
        Tech_2: "Power BI",
        Tech_3: "SQL",
        Days: "12 Days",
        rating: "4.9",
        views: "(128)",
        bg1: "bg-indigo-200",
        text1: "text-indigo-600",
        bg2: "bg-blue-200",
        text2: "text-blue-600",
        bg3: "bg-green-200",
        text3: "text-green-600",
    },

    {
        id: 40,
        department: "Commerce",
        course: "CA",
        level: "Advanced",
        image: analytics,
        name: "Tax Calculator",
        paragraph: "A calculator application for estimating taxes and organizing financial information",
        Tech_1: "Excel",
        Tech_2: "Python",
        Tech_3: "SQL",
        Days: "8 Days",
        rating: "4.7 (96)",
        bg1: "bg-red-200",
        text1: "text-red-600",
        bg2: "bg-orange-200",
        text2: "text-orange-600",
        bg3: "bg-yellow-200",
        text3: "text-yellow-600",
    },

    {
        id: 41,
        department: "Commerce",
        course: "Accounting & Finance",
        level: "Beginner",
        image: e_commerce,
        name: "Expense Tracker",
        paragraph: "An application for tracking daily expenses, income and personal budgets",
        Tech_1: "Excel",
        Tech_2: "SQL",
        Tech_3: "Power BI",
        Days: "6 Days",
        rating: "4.6",
        views: "(105)",
        bg1: "bg-green-200",
        text1: "text-green-600",
        bg2: "bg-emerald-200",
        text2: "text-emerald-600",
        bg3: "bg-teal-200",
        text3: "text-teal-600",
    },

    {
        id: 42,
        department: "Commerce",
        course: "Accounting & Finance",
        level: "Advanced",
        image: analytics,
        name: "Budget Analysis Dashboard",
        paragraph: "A dashboard for analyzing budgets, expenses and financial performance",
        Tech_1: "Excel",
        Tech_2: "Power BI",
        Tech_3: "Tableau",
        Days: "12 Days",
        rating: "4.8",
        views: "(118)",
        bg1: "bg-cyan-200",
        text1: "text-cyan-600",
        bg2: "bg-blue-200",
        text2: "text-blue-600",
        bg3: "bg-indigo-200",
        text3: "text-indigo-600",
    },

    {
        id: 43,
        department: "Commerce",
        course: "BBA",
        level: "Beginner",
        image: task,
        name: "Business Task Manager",
        paragraph: "A task management application for organizing business activities and team work",
        Tech_1: "Excel",
        Tech_2: "Power BI",
        Tech_3: "SQL",
        Days: "7 Days",
        rating: "4.7",
        views: "(90)",
        bg1: "bg-purple-200",
        text1: "text-purple-600",
        bg2: "bg-pink-200",
        text2: "text-pink-600",
        bg3: "bg-violet-200",
        text3: "text-violet-600",
    },

    {
        id: 44,
        department: "Commerce",
        course: "BBA",
        level: "Intermediate",
        image: analytics,
        name: "Sales Analytics Dashboard",
        paragraph: "A dashboard for tracking sales, revenue, customers and business growth",
        Tech_1: "Power BI",
        Tech_2: "SQL",
        Tech_3: "Excel",
        Days: "10 Days",
        rating: "4.8",
        views: "(134)",
        bg1: "bg-blue-200",
        text1: "text-blue-600",
        bg2: "bg-green-200",
        text2: "text-green-600",
        bg3: "bg-yellow-200",
        text3: "text-yellow-600",
    },

    {
        id: 45,
        department: "Commerce",
        course: "B.Com",
        level: "Advanced",
        image: analytics,
        name: "Business Finance Dashboard",
        paragraph: "A complete dashboard for monitoring business finance, revenue and expenses",
        Tech_1: "Power BI",
        Tech_2: "SQL",
        Tech_3: "Tableau",
        Days: "14 Days",
        rating: "4.9",
        views: "(145)",
        bg1: "bg-emerald-200",
        text1: "text-emerald-600",
        bg2: "bg-blue-200",
        text2: "text-blue-600",
        bg3: "bg-indigo-200",
        text3: "text-indigo-600",
    },

];


const Projects = ({ selectDept, selectCourse, selectLevel, selectTech, selectSort }) => {

    const filterProjects = projects
        .filter((card) => {
            return (
                (selectDept === "" || card.department === selectDept) &&
                (selectCourse === "" || card.course === selectCourse) &&
                (selectLevel === "" || card.level === selectLevel) &&
                (
                    selectTech === "" ||
                    card.Tech_1 === selectTech ||
                    card.Tech_2 === selectTech ||
                    card.Tech_3 === selectTech
                )
            );
        })
        .sort((a, b) => {

            if (selectSort === "Highest Rated") {
                return Number(b.rating) - Number(a.rating);
            }

            return 0;
        });
    return (
        <div className="grid grid-cols-4 gap-4 w-full">
            {filterProjects.map((card) => (
                <Product_card
                    key={card.id}
                    image={card.image}
                    name={card.name}
                    paragraph={card.paragraph}
                    Tech_1={card.Tech_1}
                    Tech_2={card.Tech_2}
                    Tech_3={card.Tech_3}
                    Days={card.Days}
                    level={card.level}
                    rating={card.rating}
                    views={card.views}
                    bg1={card.bg1}
                    text1={card.text1}
                    bg2={card.bg2}
                    text2={card.text2}
                    bg3={card.bg3}
                    text3={card.text3}
                />

            ))};



        </div>
    );
};

export default Projects;
